const $=id=>document.getElementById(id);let logFiles=[],cal=null,calTimer=null;
function fmtSize(n){if(n>1048576)return(n/1048576).toFixed(1)+' MB';if(n>1024)return(n/1024).toFixed(1)+' KB';return n+' B'}
function setDuration(v){if(v==='infinite'){$('durationMode').value='infinite';$('durationField').classList.add('hidden')}else{$('durationMode').value='finite';$('durationSeconds').value=v;$('durationField').classList.remove('hidden')}}
function updateFlowWarning(){const f=parseFloat($('targetFlow').value);let msg='';if(cal&&cal.loaded&&(f<cal.minFlow||f>cal.maxFlow))msg='Fuera del rango calibrado: '+cal.minFlow.toFixed(2)+' a '+cal.maxFlow.toFixed(2)+' L/min';$('flowWarning').textContent=msg}
async function loadStatus(){const r=await fetch('/api/status');const s=await r.json();cal=s.calibration;$('statusPills').innerHTML='<span class="pill '+(s.sdReady?'ok':'bad')+'">SD '+s.sdStatus+'</span><span class="pill">RTC '+s.rtc+'</span><span class="pill">Switch espera '+s.switches.wait+'</span>';$('waitSeconds').value=s.defaults.waitSeconds;$('targetFlow').value=Number(s.defaults.targetFlow).toFixed(1);setDuration(s.defaults.durationSeconds===4294967295?'infinite':s.defaults.durationSeconds);$('calibrationText').textContent=s.calibration.loaded?'Calibracion '+s.calibration.minFlow.toFixed(2)+' a '+s.calibration.maxFlow.toFixed(2)+' L/min':'Sin calibracion cargada';updateFlowWarning()}
async function loadLogs(){const body=$('logsBody');body.innerHTML='<tr><td colspan="3">Cargando...</td></tr>';const r=await fetch('/api/logs');if(!r.ok){body.innerHTML='<tr><td colspan="3">SD no disponible</td></tr>';return}const j=await r.json();logFiles=j.files||[];if(!logFiles.length){body.innerHTML='<tr><td colspan="3">Sin CSV disponibles</td></tr>';return}body.innerHTML=logFiles.map(f=>'<tr><td>'+f.name+'</td><td>'+fmtSize(f.size)+'</td><td><button class="link" data-preview="'+f.name+'">Ver</button> <a href="/download?file='+encodeURIComponent(f.name)+'">Descargar</a></td></tr>').join('')}
async function loadCalibration(){const r=await fetch('/api/calibration/status');const c=await r.json();$('calStatus').textContent='Estado '+c.state+' | PWM '+c.currentPwm+' | puntos '+c.points+' | rango '+Number(c.minFlow).toFixed(2)+'-'+Number(c.maxFlow).toFixed(2)+' L/min'+(c.error?' | '+c.error:'');$('calPoints').textContent=(c.data&&c.data.length)?['PWM,flow,stddev'].concat(c.data.map(p=>p.pwm+','+Number(p.flow).toFixed(2)+','+Number(p.stddev).toFixed(3))).join('\n'):'Sin puntos.';if(c.running&&!calTimer)calTimer=setInterval(loadCalibration,1500);if(!c.running&&calTimer){clearInterval(calTimer);calTimer=null}if(c.config){$('calPwmStart').value=c.config.pwmStart||$('calPwmStart').value;$('calPwmEnd').value=c.config.pwmEnd||$('calPwmEnd').value;$('calPwmStep').value=c.config.pwmStep||$('calPwmStep').value;$('calSettleMs').value=c.config.settleMs||$('calSettleMs').value;$('calSampleMs').value=c.config.sampleIntervalMs||$('calSampleMs').value;$('calSamples').value=c.config.samplesPerPoint||$('calSamples').value;$('calMaxFlow').value=c.config.maxTargetFlow||$('calMaxFlow').value}}
async function preview(name){const r=await fetch('/api/logs/preview?file='+encodeURIComponent(name));const j=await r.json();$('preview').textContent=[j.header].concat(j.rows||[]).join('\n')}
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.wait)$('waitSeconds').value=t.dataset.wait;if(t.dataset.duration)setDuration(t.dataset.duration);if(t.dataset.preview)preview(t.dataset.preview);updateFlowWarning()});
$('durationMode').addEventListener('change',e=>setDuration(e.target.value==='infinite'?'infinite':$('durationSeconds').value||300));
$('targetFlow').addEventListener('input',updateFlowWarning);
$('refreshLogs').addEventListener('click',loadLogs);
$('downloadAll').addEventListener('click',()=>logFiles.forEach((f,i)=>setTimeout(()=>{location.href='/download?file='+encodeURIComponent(f.name)},i*450)));
$('calRefresh').addEventListener('click',loadCalibration);
$('calAbort').addEventListener('click',async()=>{await fetch('/api/calibration/abort',{method:'POST'});loadCalibration()});
$('calClear').addEventListener('click',async()=>{await fetch('/api/calibration/clear',{method:'POST'});loadCalibration()});
$('calForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new URLSearchParams(new FormData(e.target));const r=await fetch('/api/calibration/start',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fd});$('preview').textContent=r.ok?'Calibracion iniciada. Mantenga flujo libre y espere finalizacion.':'No se pudo iniciar calibracion.';loadCalibration()});
$('setupForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new URLSearchParams(new FormData(e.target));if($('durationMode').value==='infinite')fd.set('durationMode','infinite');const r=await fetch('/api/confirm',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fd});$('preview').textContent=r.ok?'Configuracion confirmada. El Wi-Fi se apagara y comenzara la sesion.':'Configuracion invalida.'});
loadStatus().then(loadLogs).then(loadCalibration);
