const $=id=>document.getElementById(id);
let logFiles=[],cal=null,calTimer=null;
function fmtSize(n){if(n>1048576)return(n/1048576).toFixed(1)+' MB';if(n>1024)return(n/1024).toFixed(1)+' KB';return n+' B'}
function notify(msg,type='info',timeout=3500){if(!document.querySelector('.toast-container')){const tc=document.createElement('div');tc.className='toast-container';document.body.appendChild(tc)}const el=document.createElement('div');el.className='toast '+(type==='success'?'success':type==='error'?'error':'');el.textContent=msg;document.querySelector('.toast-container').appendChild(el);setTimeout(()=>{el.style.opacity='0';setTimeout(()=>el.remove(),300)},timeout)}
function setDuration(v){if(v==='infinite'){$('durationMode').value='infinite';$('durationField').classList.add('hidden')}else{$('durationMode').value='finite';$('durationSeconds').value=v;$('durationField').classList.remove('hidden')}}
function updateFlowWarning(){const f=parseFloat($('targetFlow').value);let msg='';if(cal&&cal.loaded&&(f<cal.minFlow||f>cal.maxFlow))msg='Fuera del rango calibrado: '+cal.minFlow.toFixed(2)+' a '+cal.maxFlow.toFixed(2)+' L/min';$('flowWarning').textContent=msg}
async function loadStatus(){try{const r=await fetch('/api/status');if(!r.ok)throw new Error('status_failed');const s=await r.json();cal=s.calibration;$('statusPills').innerHTML='<span class="pill '+(s.sdReady?'ok':'bad')+'">SD '+s.sdStatus+'</span><span class="pill">RTC '+formatRtc(s.rtc)+'</span><span class="pill">Switch espera '+s.switches.wait+'</span>';$('waitSeconds').value=s.defaults.waitSeconds;$('targetFlow').value=Number(s.defaults.targetFlow).toFixed(1);setDuration(s.defaults.durationSeconds===4294967295?'infinite':s.defaults.durationSeconds);$('calibrationText').textContent=s.calibration.loaded?'Calibración '+s.calibration.minFlow.toFixed(2)+' a '+s.calibration.maxFlow.toFixed(2)+' L/min':'Sin calibración cargada';updateFlowWarning()}catch(e){console.warn('No se pudo obtener status',e);$('statusPills').innerHTML='<span class="pill bad">Estado no disponible</span>'}}
function formatRtc(s){try{const d=new Date(s);if(isNaN(d))return s;return d.toLocaleString()}catch(e){return s}}
async function loadLogs(){const body=$('logsBody');body.innerHTML='<tr><td colspan="3">Cargando...</td></tr>';try{const r=await fetch('/api/logs');if(!r.ok){body.innerHTML='<tr><td colspan="3">SD no disponible</td></tr>';return}const j=await r.json();logFiles=j.files||[];if(!logFiles.length){body.innerHTML='<tr><td colspan="3">Sin CSV disponibles</td></tr>';return}body.innerHTML=logFiles.map(f=>'<tr><td>'+f.name+'</td><td>'+fmtSize(f.size)+'</td><td><button class="link" data-preview="'+f.name+'">Ver</button> <a class="link" href="/download?file='+encodeURIComponent(f.name)+'">Descargar</a></td></tr>').join('')}catch(e){body.innerHTML='<tr><td colspan="3">Error al listar</td></tr>'}}
async function loadCalibration(){try{const r=await fetch('/api/calibration/status');if(!r.ok)throw new Error('cal_failed');const c=await r.json();$('calStatus').textContent='Estado '+c.state+' | PWM '+c.currentPwm+' | puntos '+c.points+' | rango '+Number(c.minFlow).toFixed(2)+'-'+Number(c.maxFlow).toFixed(2)+' L/min'+(c.error?' | '+c.error:'');$('calPoints').textContent=(c.data&&c.data.length)?['PWM,flow,stddev'].concat(c.data.map(p=>p.pwm+','+Number(p.flow).toFixed(2)+','+Number(p.stddev).toFixed(3))).join('\n'):'Sin puntos.';if(c.running&&!calTimer)calTimer=setInterval(loadCalibration,1500);if(!c.running&&calTimer){clearInterval(calTimer);calTimer=null}if(c.config){$('calPwmStart').value=c.config.pwmStart||$('calPwmStart').value;$('calPwmEnd').value=c.config.pwmEnd||$('calPwmEnd').value;$('calPwmStep').value=c.config.pwmStep||$('calPwmStep').value;$('calSettleMs').value=c.config.settleMs||$('calSettleMs').value;$('calSampleMs').value=c.config.sampleIntervalMs||$('calSampleMs').value;$('calSamples').value=c.config.samplesPerPoint||$('calSamples').value;$('calMaxFlow').value=c.config.maxTargetFlow||$('calMaxFlow').value}}catch(e){console.warn('cal load failed',e);$('calStatus').textContent='Estado: no disponible'}}
async function preview(name){try{const r=await fetch('/api/logs/preview?file='+encodeURIComponent(name));if(!r.ok){$('preview').textContent='No se pudo cargar preview.';return}const j=await r.json();$('preview').textContent=[j.header].concat(j.rows||[]).join('\n')}catch(e){$('preview').textContent='Error al obtener preview.'}}

document.addEventListener('click',e=>{const t=e.target;if(t.dataset.wait)$('waitSeconds').value=t.dataset.wait;if(t.dataset.duration)setDuration(t.dataset.duration);if(t.dataset.preview)preview(t.dataset.preview);updateFlowWarning()});
$('durationMode').addEventListener('change',e=>setDuration(e.target.value==='infinite'?'infinite':$('durationSeconds').value||300));
$('targetFlow').addEventListener('input',updateFlowWarning);
$('refreshLogs').addEventListener('click',loadLogs);
$('downloadAll').addEventListener('click',()=>{if(!logFiles.length){notify('No hay archivos para descargar','info');return;}logFiles.forEach((f)=>{const a=document.createElement('a');a.href='/download?file='+encodeURIComponent(f.name);a.setAttribute('download',f.name);a.style.display='none';document.body.appendChild(a);a.click();a.remove();})});
$('calRefresh').addEventListener('click',loadCalibration);
$('calAbort').addEventListener('click',async()=>{try{await fetch('/api/calibration/abort',{method:'POST'});notify('Calibración abortada','success');loadCalibration()}catch(e){notify('No se pudo abortar','error')}});
$('calClear').addEventListener('click',async()=>{try{await fetch('/api/calibration/clear',{method:'POST'});notify('Calibración borrada','success');loadCalibration()}catch(e){notify('No se pudo borrar','error')}});
$('calForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.target.querySelector('button[type="submit"]');btn.disabled=true;const orig=btn.textContent;btn.textContent='Iniciando...';const fd=new URLSearchParams(new FormData(e.target));try{const r=await fetch('/api/calibration/start',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fd});if(r.ok){notify('Calibración iniciada. Mantenga flujo libre y espere finalización.','success')}else{const j=await r.json().catch(()=>null);notify('No se pudo iniciar calibración: '+(j&&j.error?j.error:'error'),'error')}loadCalibration()}catch(e){notify('Error al iniciar calibración','error')}btn.disabled=false;btn.textContent=orig});
$('setupForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('confirmBtn');btn.disabled=true;const orig=btn.textContent;btn.textContent='Enviando...';const fd=new URLSearchParams(new FormData(e.target));if($('durationMode').value==='infinite')fd.set('durationMode','infinite');try{const r=await fetch('/api/confirm',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fd});if(r.ok){notify('Configuración confirmada. El Wi‑Fi se apagará y comenzará la sesión.','success');$('preview').textContent='Configuración confirmada.'}else{const j=await r.json().catch(()=>null);notify('Configuración inválida: '+(j&&j.error?j.error:'error'),'error');$('preview').textContent='Configuración inválida.'}}catch(e){notify('Error enviando configuración','error')}btn.disabled=false;btn.textContent=orig});

// Inicializar
loadStatus().then(loadLogs).then(loadCalibration);
