; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = eolo_express
extra_configs = platformio.demos.ini

[env]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BME280 Library@^2.3.0
	olikraus/U8g2@^2.36.14
	sparkfun/SparkFun_FS3000_Arduino_Library@^1.0.5
	adafruit/RTClib@^2.1.4
	4-20ma/ModbusMaster@^2.0.1
	plerup/EspSoftwareSerial@^8.2.0
	vshymanskyy/TinyGSM@^0.12.0
	bblanchon/ArduinoJson@^6.20.0
lib_ldf_mode = deep+
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
upload_speed = 921600
board_build.partitions = min_spiffs.csv
extra_scripts = scripts/platformio_sync_time.py
build_unflags =
	-std=gnu++11
build_flags = 
	-std=gnu++17
	-DCORE_DEBUG_LEVEL=3
	-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DCONFIG_ESP32_PANIC_PRINT_REBOOT
	-DPROFILE_ENABLED=1
	-DPROFILE_VERBOSE=0

[env:eolo_express]
build_flags = 
	${env.build_flags}
	-DEOLO_TARGET_EXPRESS
	-DFEATURE_MOTOR_PWM
	-DFEATURE_FLOW_AFM07
	-DFEATURE_PLANTOWER

[env:eolo_express_legacy]
build_flags = 
	${env.build_flags}
	-DEOLO_TARGET_EXPRESS_LEGACY
	-DFEATURE_MOTOR_PWM
	-DFEATURE_FLOW_FS3000
	-DFEATURE_PLANTOWER

[env:eolo_standard]
build_flags = 
	${env.build_flags}
	-DEOLO_TARGET_STANDARD
	-DFEATURE_MOTOR_PWM
	-DFEATURE_MODEM
	-DFEATURE_ANEMOMETER
	-DFEATURE_DUAL_BATTERY
	-DFEATURE_FLOW_AFM07
	-DFEATURE_PLANTOWER

[env:eolo_dron]
extra_scripts =
	${env.extra_scripts}
	pre:scripts/generate_headless_setup_web.py
build_flags =
	${env.build_flags}
	-DEOLO_TARGET_DRON
	-DFEATURE_HEADLESS
	-DFEATURE_MOTOR_PWM_POWER_PIN
	-DFEATURE_FLOW_AFM07
	-DFEATURE_NEOPIXEL
	-DFEATURE_NTC
	-DDRONE_SWITCHES_HAVE_EXTERNAL_PULLS
	-DMOTOR_RAMP_STEP=16
	-DMOTOR_RAMP_INTERVAL_MS=8
	-DMOTOR_FLOW_CONTROL_MODE=MOTOR_FLOW_CONTROL_CLOSED_LOOP
lib_deps =
	${env.lib_deps}
	adafruit/Adafruit NeoPixel@^1.12.5

[env:eolo_dron_low_power]
extends = env:eolo_dron
build_flags =
	${env:eolo_dron.build_flags}
	-DSTATUS_LED_LOW_POWER
