; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = eolo_chico

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	olikraus/U8g2@^2.36.14
	sparkfun/SparkFun_FS3000_Arduino_Library@^1.0.5
	adafruit/RTClib@^2.1.4
	4-20ma/ModbusMaster@^2.0.1
	plerup/EspSoftwareSerial@^8.2.0
	vshymanskyy/TinyGSM@^0.12.0
lib_ldf_mode = deep+
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
upload_speed = 921600
board_build.partitions = min_spiffs.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DCONFIG_ESP32_PANIC_PRINT_REBOOT

[env:eolo_chico]
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	olikraus/U8g2@^2.36.14
	sparkfun/SparkFun_FS3000_Arduino_Library@^1.0.5
	adafruit/RTClib@^2.1.4
	4-20ma/ModbusMaster@^2.0.1
	plerup/EspSoftwareSerial@^8.2.0
	vshymanskyy/TinyGSM@^0.12.0

[env:eolo_grande]
build_flags = 
	-DEOLO_GRANDE
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	olikraus/U8g2@^2.36.14
	sparkfun/SparkFun_FS3000_Arduino_Library@^1.0.5
	adafruit/RTClib@^2.1.4
	4-20ma/ModbusMaster@^2.0.1
	plerup/EspSoftwareSerial@^8.2.0
	vshymanskyy/TinyGSM@^0.12.0