#!/usr/bin/env python3
from demo_config import MODELS, PROJECT_ROOT, config_for, demo_sketches, env_name


HEADER = """; Generated by scripts/generate_demo_envs.py
; Do not edit manually. Re-run the generator after adding or renaming demos.

"""


def emit_env(demo_name, sketch_path, model, model_macro, lib_deps):
    rel_sketch = sketch_path.as_posix()
    lines = [
        f"[env:{env_name(demo_name, model)}]",
        "extends = env",
        "build_src_filter = -<*>",
        "extra_scripts =",
        "\tpre:scripts/platformio_build_demo.py",
        "\tpost:scripts/platformio_demo_targets.py",
        "build_flags =",
        "\t${env.build_flags}",
        f"\t-D{model_macro}",
        f"custom_demo_src = {rel_sketch}",
        f"custom_demo_name = {demo_name}",
        f"custom_demo_model = {model}",
    ]

    if lib_deps:
        lines.append("lib_deps =")
        for dep in lib_deps:
            lines.append(f"\t{dep}")

    return "\n".join(lines) + "\n\n"


def main():
    chunks = [HEADER]
    for sketch in demo_sketches():
        demo_name = sketch.parent.name
        cfg = config_for(demo_name)
        for model in cfg["models"]:
            chunks.append(emit_env(
                demo_name=demo_name,
                sketch_path=sketch.relative_to(PROJECT_ROOT),
                model=model,
                model_macro=MODELS[model],
                lib_deps=cfg["lib_deps"],
            ))

    output = "".join(chunks)
    with open(PROJECT_ROOT / "platformio.demos.ini", "w", encoding="utf-8", newline="\n") as f:
        f.write(output)


if __name__ == "__main__":
    main()
